//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/InputConfiguration.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputConfiguration : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputConfiguration()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputConfiguration"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""d5313cf5-9989-4b05-bcfa-3ba6f3130c49"",
            ""actions"": [
                {
                    ""name"": ""Mouse position"",
                    ""type"": ""Value"",
                    ""id"": ""1e013d5d-7d10-4934-8d2f-7b4935c0d027"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Mouse clicks"",
                    ""type"": ""Button"",
                    ""id"": ""d6e360d6-de8c-4719-bcbb-9e1914530942"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c096e0a8-de27-4e7b-b837-5939217252c7"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""830755e4-c15d-4be6-a24d-961162a9d110"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse clicks"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Main
        m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
        m_Main_Mouseposition = m_Main.FindAction("Mouse position", throwIfNotFound: true);
        m_Main_Mouseclicks = m_Main.FindAction("Mouse clicks", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main
    private readonly InputActionMap m_Main;
    private IMainActions m_MainActionsCallbackInterface;
    private readonly InputAction m_Main_Mouseposition;
    private readonly InputAction m_Main_Mouseclicks;
    public struct MainActions
    {
        private @InputConfiguration m_Wrapper;
        public MainActions(@InputConfiguration wrapper) { m_Wrapper = wrapper; }
        public InputAction @Mouseposition => m_Wrapper.m_Main_Mouseposition;
        public InputAction @Mouseclicks => m_Wrapper.m_Main_Mouseclicks;
        public InputActionMap Get() { return m_Wrapper.m_Main; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
        public void SetCallbacks(IMainActions instance)
        {
            if (m_Wrapper.m_MainActionsCallbackInterface != null)
            {
                @Mouseposition.started -= m_Wrapper.m_MainActionsCallbackInterface.OnMouseposition;
                @Mouseposition.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnMouseposition;
                @Mouseposition.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnMouseposition;
                @Mouseclicks.started -= m_Wrapper.m_MainActionsCallbackInterface.OnMouseclicks;
                @Mouseclicks.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnMouseclicks;
                @Mouseclicks.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnMouseclicks;
            }
            m_Wrapper.m_MainActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Mouseposition.started += instance.OnMouseposition;
                @Mouseposition.performed += instance.OnMouseposition;
                @Mouseposition.canceled += instance.OnMouseposition;
                @Mouseclicks.started += instance.OnMouseclicks;
                @Mouseclicks.performed += instance.OnMouseclicks;
                @Mouseclicks.canceled += instance.OnMouseclicks;
            }
        }
    }
    public MainActions @Main => new MainActions(this);
    public interface IMainActions
    {
        void OnMouseposition(InputAction.CallbackContext context);
        void OnMouseclicks(InputAction.CallbackContext context);
    }
}
